// import '../styles/globals.css';
// import { Inter } from 'next/font/google';


// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
     
//         <main className="pt-16">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }



import '../styles/globals.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'kimmymae.ai',
  description: 'The Kimmymae.AI Platform',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  )
}